version: '3'

services:
  db:
    image: 'valentynchepiha/oracle18xe:18.4.0-xe'
    container_name: db
    restart: always
    environment:
      - ORACLE_PWD=Fg6dg6es78etf8g
    ports:
      - "1521:1521"
      - "5500:5500"
    healthcheck:
          test: ["CMD", "/opt/oracle/checkDBStatus.sh"]
          interval: 30s
          timeout: 30s
          retries: 30
    volumes:
      - './container/oracle18xe:/opt/oracle/oradata'
      - './startup:/opt/oracle/scripts/startup'

  server:
    image: 'valentynchepiha/nc-eshop-docker:latest'
    container_name: server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/xepdb1
      - SPRING_DATASOURCE_USERNAME=nceshop
      - SPRING_DATASOURCE_PASSWORD=f43sdg5egw54segs
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    ports:
      - "8090:8090"

  client:
    image: 'valentynchepiha/nc-eclient-docker:latest'
    container_name: client
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/xepdb1
      - SPRING_DATASOURCE_USERNAME=nceclient
      - SPRING_DATASOURCE_PASSWORD=nrfhiw832hfoef
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - API_URL_LOAD_GOODS=http://server:8090/api/goods
      - API_URL_CREATE_ORDER=http://server:8090/api/order/create
    ports:
      - "8099:8099"


